using System.Collections.Generic;
using UnityEngine;

public enum BodySide
{
    BODY_SIDE_LEFT = 0,
    BODY_SIDE_RIGHT = 1,
    BODY_SIDE_ALTERNATED = 2,
    BODY_SIDE_RANDOMLY = 3,
    BODY_SIDE_ANY = 4,
    BODY_SIDE_COUNT
}

public enum GameUseType
{
    CLINICAL_USE = 0,
    HOME_USE = 1
}

/// <summary>
/// Callback for the stop event generated by the exergame.
/// </summary>
/// <param name="output">The output data of the application in JSON format.</param>
public delegate void OnStop(string output);

public delegate void OnEventsUpdate(List<string> eventNames);

public delegate void OnNoteInformation(string noteInformation);

public delegate void OnHDCMessage(string message);

public delegate void OnIterationCompleted();

public abstract class SessionContainerBase : MonoBehaviour
{
    protected OnEventsUpdate _onEventsUpdate;
    protected OnNoteInformation _onNoteInformation;
    protected OnStop _onStop;
    protected OnHDCMessage _onHDCMessage;
    protected OnIterationCompleted _onIterationCompleted;

    /// <summary>
    /// Event called when the main VR application notifies the exergame to start
    /// in a clinical context.
    /// </summary>
    /// <param name="json">The input data of the exergame in JSON format.</param>
    public virtual void OnInit(string json) { }

    /// <summary>
    /// Event called when the main VR application notifies the exergame to start
    /// in a home use context.
    /// </summary>
    /// <param name="json">The input data of the exergame in JSON format.</param>
    public virtual void OnInitHomeUse(string json) { }

    /// <summary>
    /// Event called when the main VR application notifies the exergame to update.
    /// </summary>
    /// <param name="json">The input data of the exergame in JSON format.</param>
    public virtual void OnUpdate(string json) { }

    /// <summary>
    /// Event called when the main VR application notifies the exergame to pause.
    /// </summary>
    /// <param name="json">The input data of the exergame in JSON format.</param>
    public virtual void OnPause(bool pause) { }

    /// <summary>
    /// Event called when the main VR application notifies the exergame to stop.
    /// </summary>
    public virtual void OnStop() { }

    /// <summary>
    /// Event called when the main VR application notifies the
    /// exergame to start a custom event.
    /// </summary>
    /// <param name="eventName">The name of the custom event.</param>
    public virtual void OnCustomEvent(string eventName) { }

    /// <summary>
    /// Method called when the game-based exercise wants to send an event to the
    /// control panel. Do not call this method directly; use the system's structure.
    /// </summary>
    /// <param name="eventNames">List of events.</param>
    public virtual void OnEventsUpdateEmit(List<string> eventNames)
    {
        if (_onEventsUpdate == null) {
            return;
            //throw new System.Exception("Error");
        }

        _onEventsUpdate(eventNames);
    }

    /// <summary>
    /// Method called when the game-based exercise wants to send a note to be
    /// recorded in the system and displayed on the therapist's control panel.
    /// </summary>
    /// <param name="noteText">The text of the note.</param>
    public virtual void OnNoteInformationSend(string noteText)
    {
        if (_onNoteInformation == null) {
            return;
            //throw new System.Exception("Error");
        }

        _onNoteInformation(noteText);
    }

    public virtual void OnHDCMessageSend(string message)
    {
        //if (_onHDCMessage == null) {
        //    return;
        //}

        _onHDCMessage(message);
    }

    /// <summary>
    /// Method called when the game-based exercise wants to notify the
    /// system about the completion of an iteration in a home use context.
    /// </summary>
    public virtual void OnIterationCompleted()
    {
        _onIterationCompleted.Invoke();
    }

    /// <summary>
    /// The registration of the event of sending constraints to the control panel
    /// operated by the therapist, generated by the game-based exercise.
    /// </summary>
    /// <param name="onEventsUpdate"></param>
    public void AttachOnEventsUpdate(OnEventsUpdate onEventsUpdate)
    {
        _onEventsUpdate = onEventsUpdate;
    }

    /// <summary>
    /// The registration of the event of sending a note to the control panel
    /// operated by the therapist, generated by the game-based exercise.
    /// </summary>
    /// <param name="onNoteInformation"></param>
    public void AttachOnNoteInformation(OnNoteInformation onNoteInformation)
    {
        _onNoteInformation = onNoteInformation;
    }

    /// <summary>
    /// The registration of the event of sending a message to the HDC,
    /// generated by the game-based exercise.
    /// </summary>
    /// <param name="onHDCMessage">The </param>
    public void AttachOnHDCMessage(OnHDCMessage onHDCMessage)
    {
        _onHDCMessage = onHDCMessage;
    }

    /// <summary>
    /// The registration of the completion event of an iteration,
    /// generated by the game-based exercise.
    /// </summary>
    /// <param name="onIterationCompleted">The completion event of an iteration.</param>
    public void AttachOnIterationCompleted(OnIterationCompleted onIterationCompleted)
    {
        _onIterationCompleted = onIterationCompleted;
    }

    /// <summary>
    /// The registration of the stop event generated by the exergame.
    /// </summary>
    /// <param name="onStop">The stop event.</param>
    public void AttachOnStop(OnStop onStop)
    {
        _onStop = onStop;
    }

    /// <summary>
    /// Event called when the HDC application notifies the exergame to update.
    /// </summary>
    /// <param name="messages">Represents a list {header, body} that includes the information transmitted from the HDC application.</param>
    public virtual void OnHDCUpdate(string[] messages) { }
}
