using Newtonsoft.Json;
using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.SceneManagement;

namespace FruitsGame
{
    public enum GameType
    {
        GAME_TYPE_BASKET = 0,
        GAME_TYPE_MOUTH = 1
    }

    public enum BodySide
    {
        BODY_SIDE_LEFT = 0,
        BODY_SIDE_RIGHT = 1,
        BODY_SIDE_BOTH = 2
    }

    public enum CountdownTimer
    {
        None = 0,
        OneMinute = 1,
        TwoMinutes = 2,
        ThreeMinutes = 3,
        FourMinutes = 4,
        FiveMinutes = 5,
    }

    /// <summary>
    /// An example of input data.
    /// Only int and bool data types are allowed at this time.
    /// </summary>
    public class InputData
    {
        public bool Haptic;
        public int NrTotalFructe;
        public int NrFructe;
        public CountdownTimer CountdownTimer;
        public int MinAngleFlexion;
        public int MaxAngleFlexion;
        public int MinAngleAbduction;
        public int MaxAngleAbduction;
        public int MinDistancePlacement;
        public int MaxDistancePlacement;
        public bool NecesitaGestPrindere;
        public int BasketScale;
        public int BasketOffsetY;
        public GameType GameType;


        // Implicite
        public int duration;
        public BodySide BodySide;
        public int UseType;

        // GardenGame
        public int PlantAngleDeg;  
        public int WaterAngleDeg;

        public int PotCount;           
        public int WorkingDistanceCm;
        public int TableHeightOffsetCm;
        public int FlowerType;
    }
    /// <summary>
    /// An example of output data.
    /// Only int and bool data types are allowed at this time.
    /// </summary>
    [Serializable]
    public class GameSessionOutputData : GameSessionOutputDataBase
    {
        public int LoadedFruitCount;
    }

    /// <summary>
    /// Callback for the stop event generated by the exergame.
    /// </summary>

    public class SessionContainer : SessionContainerBase
    {
        [SerializeField]
        protected InputData _inputData;

        [SerializeField]
        protected ClinicalUseController _clinicalUseController;
        [SerializeField]
        protected HomeUseController _homeUseController;
        protected GameManagerBase _mainController;

        void Start()
        {
    #if (UNITY_EDITOR)
            //OnInit("{\"NrFructe\":\"5\"," +
            //    "\"NrTotalFructe\":\"20\"," +
            //    " \"NecesitaGestPrindere\":\"false\"," +
            //    "\"BodySide\":\"0\"," +
            //    "\"duration\":\"0\"," +
            //    "\"MinAngleFlexion\":\"45\"," +
            //    "\"MaxAngleFlexion\":\"60\"," +
            //    "\"MinAngleAbduction\":\"30\"," +
            //    "\"MaxAngleAbduction\":\"50\"," +
            //    "\"MinDistancePlacement\":\"30\"," +
            //    "\"MaxDistancePlacement\":\"100\"," +
            //    "\"BasketScale\":\"100\"," +
            //    "\"GameType\":\"0\"," +
            //    "\"BasketOffsetY\":\"0\"}");
    #endif

        }

        /// <summary>
        /// Event called when the main VR application notifies the exergame to start.
        /// </summary>
        /// <param name="json">The input data of the exergame in JSON format.</param>
        /// 
        public override void OnInit(string json)
        {
            _inputData = JsonUtility.FromJson<InputData>(json);
            _inputData.UseType = 0; // Clinical

            _clinicalUseController.Init(_inputData);
            _mainController = _clinicalUseController;
        }

        public override void OnInitHomeUse(string json)
        {
            _inputData = JsonUtility.FromJson<InputData>(json);
            _inputData.UseType = 1; // Home

            _homeUseController.Init(_inputData);
            _mainController = _homeUseController;
        }

        public override void OnUpdate(string json)
        {
            _inputData = JsonUtility.FromJson<InputData>(json);

            _clinicalUseController.UpdateGame(_inputData);
        }

        /// <summary>
        /// Event called when the main VR application notifies the exergame to pause.
        /// </summary>
        public override void OnPause(bool pause)
        {
            //CubeGameManager.instance.Pause(pause);
        }

        /// <summary>
        /// Event called when the main VR application notifies the
        /// exergame to start a custom event.
        /// </summary>
        /// <param name="eventName">The name of the custom event.</param>
        public override void OnCustomEvent(string eventName)
        {
            Debug.Log(eventName);

            if (eventName == "startgame") {
                _clinicalUseController.StartGame();
            }

            if (eventName == "stopgame") {
                _clinicalUseController.StopGame();
            }
        }

        /// <summary>
        /// Event called when the main VR application notifies the exergame to stop.
        /// </summary>
        public override void OnStop()
        {
            if (_onStop == null) {
                return;
            }

            var outputData = _mainController.OutputData;

            string output = JsonConvert.SerializeObject(outputData);

            _onStop(output);
        }
    }
}
